/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.DosenControl;
import Exception.InputEmptyException;
import Exception.NoIndukDosenException;
import Model.Dosen;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author fikaa
 */
public final class DosenView extends javax.swing.JFrame {

  private final DosenControl dosenControl;
  String action = null;

  /**
   * Creates new form DosenView
   */
  public DosenView() {
    initComponents();
    setComponent(false);
    setEditDeleteBtn(false);
    dosenControl = new DosenControl();
    showDosen();
  }

  public void setComponent(boolean value) {
    nidInput.setEnabled(value);
    namaInput.setEnabled(value);
    emailInput.setEnabled(value);
    handphoneInput.setEnabled(value);

    saveBtn.setEnabled(value);
    cancelBtn.setEnabled(value);
  }

  public void setEditDeleteBtn(boolean value) {
    editBtn.setEnabled(value);
    deleteBtn.setEnabled(value);
  }

  public void clearText() {
    nidInput.setText("");
    namaInput.setText("");
    emailInput.setText("");
    handphoneInput.setText("");
    inputSearch.setText("");
  }

  public void showDosen() {
    showDataTextArea.setText(dosenControl.showAllDataDosen());
  }

  public void inputKosongException() throws InputEmptyException {
    if (nidInput.getText().isEmpty() || namaInput.getText().isEmpty() || emailInput.getText().isEmpty() || handphoneInput.getText().isEmpty()) {
      throw new InputEmptyException();
    }
  }

  public void noIndukDosenException() throws NoIndukDosenException {
    if (nidInput.getText().length() != 5) {
      throw new NoIndukDosenException();
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    sidebarPanel = new javax.swing.JPanel();
    lecturerPanel = new javax.swing.JPanel();
    lecturerLabel = new javax.swing.JLabel();
    containerPanel = new javax.swing.JPanel();
    titleContent = new javax.swing.JLabel();
    addBtn = new javax.swing.JButton();
    editBtn = new javax.swing.JButton();
    deleteBtn = new javax.swing.JButton();
    searchBtn = new javax.swing.JButton();
    inputSearch = new javax.swing.JTextField();
    containerInputNID = new javax.swing.JPanel();
    nidLabel = new javax.swing.JLabel();
    nidInput = new javax.swing.JTextField();
    containerInputNama = new javax.swing.JPanel();
    namaLabel = new javax.swing.JLabel();
    namaInput = new javax.swing.JTextField();
    containerInputEmail = new javax.swing.JPanel();
    emailLabel = new javax.swing.JLabel();
    emailInput = new javax.swing.JTextField();
    containerInputHandphone = new javax.swing.JPanel();
    handphoneLabel = new javax.swing.JLabel();
    handphoneInput = new javax.swing.JTextField();
    saveBtn = new javax.swing.JButton();
    cancelBtn = new javax.swing.JButton();
    showDataPanel = new javax.swing.JScrollPane();
    showDataTextArea = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("DosenView - 11385");
    setPreferredSize(new java.awt.Dimension(850, 660));
    setResizable(false);

    javax.swing.GroupLayout lecturerPanelLayout = new javax.swing.GroupLayout(lecturerPanel);
    lecturerPanel.setLayout(lecturerPanelLayout);
    lecturerPanelLayout.setHorizontalGroup(
      lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    lecturerPanelLayout.setVerticalGroup(
      lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );

    lecturerLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
    lecturerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lecturerLabel.setText("Dosen");

    javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
    sidebarPanel.setLayout(sidebarPanelLayout);
    sidebarPanelLayout.setHorizontalGroup(
      sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(sidebarPanelLayout.createSequentialGroup()
        .addComponent(lecturerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 12, Short.MAX_VALUE))
      .addGroup(sidebarPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lecturerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    sidebarPanelLayout.setVerticalGroup(
      sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(sidebarPanelLayout.createSequentialGroup()
        .addComponent(lecturerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lecturerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        .addGap(370, 370, 370))
    );

    titleContent.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
    titleContent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titleContent.setText("DOSEN");

    addBtn.setText("Tambah");
    addBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addBtnActionPerformed(evt);
      }
    });

    editBtn.setText("Ubah");
    editBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        editBtnActionPerformed(evt);
      }
    });

    deleteBtn.setText("Hapus");
    deleteBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteBtnActionPerformed(evt);
      }
    });

    searchBtn.setText("Cari");
    searchBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchBtnActionPerformed(evt);
      }
    });

    containerInputNID.setPreferredSize(new java.awt.Dimension(300, 65));

    nidLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
    nidLabel.setText("Nomor Induk Dosen");

    javax.swing.GroupLayout containerInputNIDLayout = new javax.swing.GroupLayout(containerInputNID);
    containerInputNID.setLayout(containerInputNIDLayout);
    containerInputNIDLayout.setHorizontalGroup(
      containerInputNIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerInputNIDLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(containerInputNIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(nidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
          .addComponent(nidInput))
        .addContainerGap())
    );
    containerInputNIDLayout.setVerticalGroup(
      containerInputNIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerInputNIDLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(nidLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(nidInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(11, Short.MAX_VALUE))
    );

    containerInputNama.setPreferredSize(new java.awt.Dimension(300, 65));

    namaLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
    namaLabel.setText("Nama");

    javax.swing.GroupLayout containerInputNamaLayout = new javax.swing.GroupLayout(containerInputNama);
    containerInputNama.setLayout(containerInputNamaLayout);
    containerInputNamaLayout.setHorizontalGroup(
      containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerInputNamaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(namaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(namaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
        .addContainerGap())
    );
    containerInputNamaLayout.setVerticalGroup(
      containerInputNamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerInputNamaLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(namaLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(11, Short.MAX_VALUE))
    );

    containerInputEmail.setPreferredSize(new java.awt.Dimension(300, 65));

    emailLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
    emailLabel.setText("Email");

    javax.swing.GroupLayout containerInputEmailLayout = new javax.swing.GroupLayout(containerInputEmail);
    containerInputEmail.setLayout(containerInputEmailLayout);
    containerInputEmailLayout.setHorizontalGroup(
      containerInputEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerInputEmailLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(containerInputEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(emailInput, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
        .addContainerGap())
    );
    containerInputEmailLayout.setVerticalGroup(
      containerInputEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerInputEmailLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(emailLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(11, Short.MAX_VALUE))
    );

    containerInputHandphone.setPreferredSize(new java.awt.Dimension(300, 65));

    handphoneLabel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
    handphoneLabel.setText("Handphone");

    javax.swing.GroupLayout containerInputHandphoneLayout = new javax.swing.GroupLayout(containerInputHandphone);
    containerInputHandphone.setLayout(containerInputHandphoneLayout);
    containerInputHandphoneLayout.setHorizontalGroup(
      containerInputHandphoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerInputHandphoneLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(containerInputHandphoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(handphoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
          .addComponent(handphoneInput))
        .addContainerGap())
    );
    containerInputHandphoneLayout.setVerticalGroup(
      containerInputHandphoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerInputHandphoneLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(handphoneLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(handphoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(11, Short.MAX_VALUE))
    );

    saveBtn.setText("Simpan");
    saveBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveBtnActionPerformed(evt);
      }
    });

    cancelBtn.setText("Batal");
    cancelBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelBtnActionPerformed(evt);
      }
    });

    showDataTextArea.setEditable(false);
    showDataTextArea.setColumns(20);
    showDataTextArea.setRows(5);
    showDataPanel.setViewportView(showDataTextArea);

    javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
    containerPanel.setLayout(containerPanelLayout);
    containerPanelLayout.setHorizontalGroup(
      containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(containerPanelLayout.createSequentialGroup()
            .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(containerInputNID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(containerInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(containerInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                  .addComponent(titleContent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(javax.swing.GroupLayout.Alignment.LEADING, containerPanelLayout.createSequentialGroup()
                    .addComponent(addBtn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(editBtn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(deleteBtn)))
                .addGap(107, 107, 107)
                .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)))
            .addContainerGap(120, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerPanelLayout.createSequentialGroup()
            .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(showDataPanel)
              .addGroup(containerPanelLayout.createSequentialGroup()
                .addComponent(containerInputHandphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelBtn)))
            .addGap(77, 77, 77))))
    );
    containerPanelLayout.setVerticalGroup(
      containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(titleContent)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(addBtn)
          .addComponent(editBtn)
          .addComponent(deleteBtn)
          .addComponent(searchBtn)
          .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(39, 39, 39)
        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(containerPanelLayout.createSequentialGroup()
            .addComponent(containerInputNID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(containerInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(containerInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(containerInputHandphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(saveBtn)
            .addComponent(cancelBtn)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(showDataPanel)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(106, 106, 106)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(containerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
    // TODO add your handling code here:
    setComponent(true);
    clearText();
    inputSearch.setText("");
    action = "Tambah";
  }//GEN-LAST:event_addBtnActionPerformed

  private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
    // TODO add your handling code here:
    setComponent(true);
    nidInput.setEnabled(false);
    action = "Ubah";
  }//GEN-LAST:event_editBtnActionPerformed

  private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
    // TODO add your handling code here:
    int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Yakin hapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

    if (getAnswer == JOptionPane.YES_OPTION) {
      try {
        dosenControl.deleteDataDosen(nidInput.getText());
        clearText();
        showDosen();
        JOptionPane.showMessageDialog(null, "Data dihapus!!!");
      } catch (HeadlessException e) {
        System.out.println("Error : " + e.getMessage());
      }
    }
  }//GEN-LAST:event_deleteBtnActionPerformed

  private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
    // TODO add your handling code here:
    setEditDeleteBtn(true);
    setComponent(false);

    try {
      Dosen dosen = dosenControl.fetchDataDosen(inputSearch.getText());
      if (dosen == null) {
        clearText();
        setEditDeleteBtn(false);
        JOptionPane.showConfirmDialog(null, "Data not found!", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
      } else {
        nidInput.setText(dosen.getNomorIndukDosen());
        namaInput.setText(dosen.getNama());
        emailInput.setText(dosen.getEmail());
        handphoneInput.setText(dosen.getNoHandphone());
      }
    } catch (HeadlessException e) {
      System.out.println("Error : " + e.getMessage());
    }
  }//GEN-LAST:event_searchBtnActionPerformed

  private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
    // TODO add your handling code here:
    try {
      inputKosongException();
      noIndukDosenException();

      Dosen d = new Dosen(nidInput.getText(), namaInput.getText(), emailInput.getText(), handphoneInput.getText());
      if (action.equals("Tambah")) {
        dosenControl.insertDataDosen(d);
      } else {
        dosenControl.updateDataDosen(d, nidInput.getText());
      }
      clearText();
      showDosen();
      setComponent(false);
      setEditDeleteBtn(false);

    } catch (InputEmptyException e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
    } catch (NoIndukDosenException e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
    }
  }//GEN-LAST:event_saveBtnActionPerformed

  private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
    // TODO add your handling code here:
    setComponent(false);
    setEditDeleteBtn(false);
    clearText();
  }//GEN-LAST:event_cancelBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(DosenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new DosenView().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addBtn;
  private javax.swing.JButton cancelBtn;
  private javax.swing.JPanel containerInputEmail;
  private javax.swing.JPanel containerInputHandphone;
  private javax.swing.JPanel containerInputNID;
  private javax.swing.JPanel containerInputNama;
  private javax.swing.JPanel containerPanel;
  private javax.swing.JButton deleteBtn;
  private javax.swing.JButton editBtn;
  private javax.swing.JTextField emailInput;
  private javax.swing.JLabel emailLabel;
  private javax.swing.JTextField handphoneInput;
  private javax.swing.JLabel handphoneLabel;
  private javax.swing.JTextField inputSearch;
  private javax.swing.JLabel lecturerLabel;
  private javax.swing.JPanel lecturerPanel;
  private javax.swing.JTextField namaInput;
  private javax.swing.JLabel namaLabel;
  private javax.swing.JTextField nidInput;
  private javax.swing.JLabel nidLabel;
  private javax.swing.JButton saveBtn;
  private javax.swing.JButton searchBtn;
  private javax.swing.JScrollPane showDataPanel;
  private javax.swing.JTextArea showDataTextArea;
  private javax.swing.JPanel sidebarPanel;
  private javax.swing.JLabel titleContent;
  // End of variables declaration//GEN-END:variables
}
