/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.DosenControl;
import Control.MataKuliahControl;
import Exception.InputEmptyException;
import Model.Dosen;
import Model.MataKuliah;
import Table.TableMataKuliah;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author fikaa
 */
public final class MataKuliahView extends javax.swing.JFrame {

  private final DosenControl dosenControl;
  private final MataKuliahControl mataKuliahControl;
  String action = null;
  List<Dosen> listDosen;
  int selectedId = 0;

  /**
   * Creates new form MataKuliahView
   */
  public MataKuliahView() {
    initComponents();

    dosenControl = new DosenControl();
    mataKuliahControl = new MataKuliahControl();

    setComponent(false);
    setRadioKelas(false);
    setEditDeleteBtn(false);
    showMataKuliah();
    setActionCommandRadio();
    setDosenToDropdown();

  }

  public void setDosenToDropdown() {
    listDosen = dosenControl.showListDosen();
    for (Dosen d : listDosen) {
      dosenDropdown.addItem(d.toString());
    }
  }

  public void setComponent(boolean value) {
    matakuliahInput.setEnabled(value);
    deskripsiInput.setEnabled(value);
    dosenDropdown.setEnabled(value);
    onlineCheckBox.setEnabled(value);
    offlineCheckBox.setEnabled(value);

    saveBtn.setEnabled(value);
    cancelBtn.setEnabled(value);
  }

  public void setRadioKelas(boolean value) {
    radio3315.setEnabled(value);
    radio3318.setEnabled(value);
    radio3421.setEnabled(value);
    radio3422.setEnabled(value);
  }

  public void setEditDeleteBtn(boolean value) {
    editBtn.setEnabled(value);
    deleteBtn.setEnabled(value);
  }

  public void clearText() {
    matakuliahInput.setText("");
    deskripsiInput.setText("");
    dosenDropdown.setSelectedItem(ABORT);
    onlineCheckBox.setSelected(false);
    offlineCheckBox.setSelected(false);

    ruangKelasGroup.clearSelection();
    inputSearch.setText("");
  }

  public void setActionCommandRadio() {
    radio3315.setActionCommand("3315");
    radio3318.setActionCommand("3318");
    radio3421.setActionCommand("3421");
    radio3422.setActionCommand("3422");
  }

  public void showMataKuliah() {
    tableMataKuliah.setModel(mataKuliahControl.showMataKuliah(""));
  }

  public void inputKosongException() throws InputEmptyException {
    if (matakuliahInput.getText().isEmpty() || deskripsiInput.getText().isEmpty() || dosenDropdown.getSelectedIndex() == -1) {
      throw new InputEmptyException();
    }

    if (!onlineCheckBox.isSelected() && !offlineCheckBox.isSelected()) {
      throw new InputEmptyException();
    }

    if (offlineCheckBox.isSelected() && ruangKelasGroup.getSelection() == null) {
      throw new InputEmptyException();
    }

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    ruangKelasGroup = new javax.swing.ButtonGroup();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    sidebarPanel = new javax.swing.JPanel();
    logo = new javax.swing.JLabel();
    lecturerPanel = new javax.swing.JPanel();
    lecturerIcon = new javax.swing.JLabel();
    lecturerLabel = new javax.swing.JLabel();
    coursePanel = new javax.swing.JPanel();
    courseIcon = new javax.swing.JLabel();
    courseLabel = new javax.swing.JLabel();
    containerPanel = new javax.swing.JPanel();
    headerPanel = new javax.swing.JPanel();
    titleContent = new javax.swing.JLabel();
    addBtn = new javax.swing.JButton();
    editBtn = new javax.swing.JButton();
    deleteBtn = new javax.swing.JButton();
    inputSearch = new javax.swing.JTextField();
    searchBtn = new javax.swing.JButton();
    contentPanel = new javax.swing.JPanel();
    matakuliahLabel = new javax.swing.JLabel();
    matakuliahInput = new javax.swing.JTextField();
    deskripsiLabel = new javax.swing.JLabel();
    deskripsiInput = new javax.swing.JTextField();
    dosenLabel = new javax.swing.JLabel();
    dosenDropdown = new javax.swing.JComboBox<>();
    metodeLabel = new javax.swing.JLabel();
    onlineCheckBox = new javax.swing.JCheckBox();
    offlineCheckBox = new javax.swing.JCheckBox();
    kelasLabel = new javax.swing.JLabel();
    radio3315 = new javax.swing.JRadioButton();
    radio3318 = new javax.swing.JRadioButton();
    radio3421 = new javax.swing.JRadioButton();
    radio3422 = new javax.swing.JRadioButton();
    saveBtn = new javax.swing.JButton();
    cancelBtn = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    tableMataKuliah = new javax.swing.JTable();

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane1.setViewportView(jTable1);

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("MataKuliahView - 11385");
    setPreferredSize(new java.awt.Dimension(860, 660));
    setResizable(false);

    sidebarPanel.setBackground(new java.awt.Color(22, 52, 122));
    sidebarPanel.setPreferredSize(new java.awt.Dimension(101, 660));

    logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logo.png"))); // NOI18N

    lecturerPanel.setBackground(new java.awt.Color(22, 52, 122));
    lecturerPanel.setToolTipText("");
    lecturerPanel.setPreferredSize(new java.awt.Dimension(101, 90));

    lecturerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lecturerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/lecturer.png"))); // NOI18N
    lecturerIcon.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        lecturerIconMouseClicked(evt);
      }
    });

    lecturerLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    lecturerLabel.setForeground(new java.awt.Color(255, 255, 255));
    lecturerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lecturerLabel.setText("Dosen");

    javax.swing.GroupLayout lecturerPanelLayout = new javax.swing.GroupLayout(lecturerPanel);
    lecturerPanel.setLayout(lecturerPanelLayout);
    lecturerPanelLayout.setHorizontalGroup(
      lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(lecturerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(lecturerPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lecturerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        .addContainerGap())
    );
    lecturerPanelLayout.setVerticalGroup(
      lecturerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(lecturerPanelLayout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addComponent(lecturerIcon)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(lecturerLabel)
        .addContainerGap(15, Short.MAX_VALUE))
    );

    coursePanel.setBackground(new java.awt.Color(7, 24, 89));
    coursePanel.setToolTipText("");
    coursePanel.setPreferredSize(new java.awt.Dimension(101, 90));

    courseIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    courseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/book.png"))); // NOI18N

    courseLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    courseLabel.setForeground(new java.awt.Color(255, 255, 255));
    courseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    courseLabel.setText("Mata Kuliah");

    javax.swing.GroupLayout coursePanelLayout = new javax.swing.GroupLayout(coursePanel);
    coursePanel.setLayout(coursePanelLayout);
    coursePanelLayout.setHorizontalGroup(
      coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(courseIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(coursePanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(courseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
        .addContainerGap())
    );
    coursePanelLayout.setVerticalGroup(
      coursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(coursePanelLayout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addComponent(courseIcon)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(courseLabel)
        .addContainerGap(15, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
    sidebarPanel.setLayout(sidebarPanelLayout);
    sidebarPanelLayout.setHorizontalGroup(
      sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lecturerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(coursePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );
    sidebarPanelLayout.setVerticalGroup(
      sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(sidebarPanelLayout.createSequentialGroup()
        .addGap(41, 41, 41)
        .addComponent(logo)
        .addGap(60, 60, 60)
        .addComponent(lecturerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(coursePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    containerPanel.setBackground(new java.awt.Color(243, 243, 243));

    headerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

    titleContent.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
    titleContent.setText("Mata Kuliah");

    addBtn.setBackground(new java.awt.Color(0, 153, 0));
    addBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    addBtn.setForeground(java.awt.Color.white);
    addBtn.setText("Tambah");
    addBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addBtnActionPerformed(evt);
      }
    });

    editBtn.setBackground(new java.awt.Color(236, 168, 30));
    editBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    editBtn.setForeground(java.awt.Color.white);
    editBtn.setText("Ubah");
    editBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        editBtnActionPerformed(evt);
      }
    });

    deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
    deleteBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    deleteBtn.setForeground(java.awt.Color.white);
    deleteBtn.setText("Hapus");
    deleteBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteBtnActionPerformed(evt);
      }
    });

    inputSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    searchBtn.setBackground(new java.awt.Color(22, 52, 122));
    searchBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    searchBtn.setForeground(java.awt.Color.white);
    searchBtn.setText("Cari");
    searchBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
    headerPanel.setLayout(headerPanelLayout);
    headerPanelLayout.setHorizontalGroup(
      headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(headerPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(titleContent)
          .addGroup(headerPanelLayout.createSequentialGroup()
            .addComponent(addBtn)
            .addGap(18, 18, 18)
            .addComponent(editBtn)
            .addGap(18, 18, 18)
            .addComponent(deleteBtn)
            .addGap(81, 81, 81)
            .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    headerPanelLayout.setVerticalGroup(
      headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(headerPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(titleContent)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(addBtn)
          .addComponent(editBtn)
          .addComponent(deleteBtn)
          .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(searchBtn))
        .addContainerGap(40, Short.MAX_VALUE))
    );

    contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));

    matakuliahLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    matakuliahLabel.setText("Mata Kuliah");

    matakuliahInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    deskripsiLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    deskripsiLabel.setText("Deskripsi");

    deskripsiInput.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    dosenLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    dosenLabel.setText("Dosen");

    dosenDropdown.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

    metodeLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    metodeLabel.setText("Metode Pembelajaran");

    onlineCheckBox.setText("Online");

    offlineCheckBox.setText("Offline");
    offlineCheckBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        offlineCheckBoxActionPerformed(evt);
      }
    });

    kelasLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    kelasLabel.setText("Kelas");

    ruangKelasGroup.add(radio3315);
    radio3315.setText("3315");

    ruangKelasGroup.add(radio3318);
    radio3318.setText("3318");

    ruangKelasGroup.add(radio3421);
    radio3421.setText("3421");

    ruangKelasGroup.add(radio3422);
    radio3422.setText("3422");

    saveBtn.setBackground(new java.awt.Color(22, 52, 122));
    saveBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    saveBtn.setForeground(java.awt.Color.white);
    saveBtn.setText("Simpan");
    saveBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveBtnActionPerformed(evt);
      }
    });

    cancelBtn.setBackground(new java.awt.Color(153, 0, 0));
    cancelBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
    cancelBtn.setForeground(java.awt.Color.white);
    cancelBtn.setText("Batal");
    cancelBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelBtnActionPerformed(evt);
      }
    });

    tableMataKuliah.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    tableMataKuliah.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tableMataKuliahMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tableMataKuliah);

    javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
    contentPanel.setLayout(contentPanelLayout);
    contentPanelLayout.setHorizontalGroup(
      contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(contentPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(contentPanelLayout.createSequentialGroup()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(contentPanelLayout.createSequentialGroup()
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(matakuliahLabel)
              .addComponent(matakuliahInput)
              .addComponent(deskripsiLabel)
              .addComponent(deskripsiInput, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
              .addComponent(dosenLabel)
              .addComponent(dosenDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(metodeLabel)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                      .addComponent(onlineCheckBox)
                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(offlineCheckBox)))
                  .addComponent(kelasLabel)
                  .addComponent(radio3315)
                  .addComponent(radio3318)
                  .addComponent(radio3421)
                  .addComponent(radio3422))
                .addContainerGap(426, Short.MAX_VALUE))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanelLayout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addGap(18, 18, 18)
                .addComponent(cancelBtn)
                .addGap(119, 119, 119))))))
    );
    contentPanelLayout.setVerticalGroup(
      contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(contentPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(matakuliahLabel)
          .addComponent(metodeLabel))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(matakuliahInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(onlineCheckBox)
          .addComponent(offlineCheckBox))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(deskripsiLabel)
          .addComponent(kelasLabel))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(contentPanelLayout.createSequentialGroup()
            .addComponent(deskripsiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(dosenLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(dosenDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(saveBtn)
              .addComponent(cancelBtn)))
          .addGroup(contentPanelLayout.createSequentialGroup()
            .addComponent(radio3315)
            .addGap(2, 2, 2)
            .addComponent(radio3318)
            .addGap(3, 3, 3)
            .addComponent(radio3421)
            .addGap(5, 5, 5)
            .addComponent(radio3422)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
    containerPanel.setLayout(containerPanelLayout);
    containerPanelLayout.setHorizontalGroup(
      containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    containerPanelLayout.setVerticalGroup(
      containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(containerPanelLayout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
        .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(34, 34, 34))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
      .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void lecturerIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerIconMouseClicked
    // TODO add your handling code here:
    DosenView dv = new DosenView();
    this.dispose();
    dv.setVisible(true);
  }//GEN-LAST:event_lecturerIconMouseClicked

  private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
    // TODO add your handling code here:
    setComponent(true);
    setRadioKelas(false);
    ruangKelasGroup.clearSelection();

    clearText();
    inputSearch.setText("");
    action = "Tambah";
    dosenDropdown.setSelectedIndex(0);
  }//GEN-LAST:event_addBtnActionPerformed

  private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
    // TODO add your handling code here:
    setComponent(true);
    action = "Ubah";
    boolean value = false;
    if (offlineCheckBox.isSelected()) {
      value = true;
    }
    setRadioKelas(value);
  }//GEN-LAST:event_editBtnActionPerformed

  private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
    // TODO add your handling code here:
    int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Yakin hapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    switch (getAnswer) {
      case 0:
        try {
        mataKuliahControl.deleteDataMataKuliah(selectedId);
        clearText();
        showMataKuliah();
        setComponent(false);
        setRadioKelas(false);
        setEditDeleteBtn(false);
        ruangKelasGroup.clearSelection();

      } catch (Exception e) {
        System.out.println("Error : " + e.getMessage());
      }
      break;
      case 1:
        break;
    }
  }//GEN-LAST:event_deleteBtnActionPerformed

  private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
    // TODO add your handling code here:
    setEditDeleteBtn(false);
    setComponent(false);

    try {
      TableMataKuliah matakuliah = mataKuliahControl.showMataKuliah(inputSearch.getText());
      if (matakuliah.getRowCount() == 0) {
        clearText();
        setEditDeleteBtn(false);
        JOptionPane.showConfirmDialog(null, "Data not found!", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
      } else {
        tableMataKuliah.setModel(matakuliah);
      }

    } catch (HeadlessException e) {
      System.out.println("Error : " + e.getMessage());
    }

  }//GEN-LAST:event_searchBtnActionPerformed

  private void offlineCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offlineCheckBoxActionPerformed
    // TODO add your handling code here:
    boolean value = false;
    if (offlineCheckBox.isSelected()) {
      value = true;
    }
    setRadioKelas(value);
    ruangKelasGroup.clearSelection();
  }//GEN-LAST:event_offlineCheckBoxActionPerformed

  private void tableMataKuliahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMataKuliahMouseClicked
    // TODO add your handling code here:
    int indexDosen = -1;
    setEditDeleteBtn(true);

    setComponent(false);
    setRadioKelas(false);
    ruangKelasGroup.clearSelection();

    int clickedRow = tableMataKuliah.getSelectedRow();
    TableModel tableModel = tableMataKuliah.getModel();

    selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 5).toString());
    matakuliahInput.setText(tableModel.getValueAt(clickedRow, 0).toString());
    deskripsiInput.setText(tableModel.getValueAt(clickedRow, 1).toString());

    String metodePembelajaran = tableModel.getValueAt(clickedRow, 3).toString();
    switch (metodePembelajaran) {
      case "Hybrid":
        onlineCheckBox.setSelected(true);
        offlineCheckBox.setSelected(true);
        break;
      case "Online":
        onlineCheckBox.setSelected(true);
        offlineCheckBox.setSelected(false);
        break;
      case "Offline":
        onlineCheckBox.setSelected(false);
        offlineCheckBox.setSelected(true);
        break;
    }

    String ruangKelas = tableModel.getValueAt(clickedRow, 4).toString();
    switch (ruangKelas) {
      case "3315":
        radio3315.setSelected(true);
        break;
      case "3318":
        radio3318.setSelected(true);
        break;
      case "3421":
        radio3421.setSelected(true);
        break;
      case "3422":
        radio3422.setSelected(true);
        break;
    }

    deskripsiInput.setText(tableModel.getValueAt(clickedRow, 1).toString());

    String nomorIndukDosen = tableModel.getValueAt(clickedRow, 6).toString();
    for (Dosen dosen : listDosen) {
      if (dosen.getNomorIndukDosen().equals(nomorIndukDosen)) {
        indexDosen = listDosen.indexOf(dosen);
      }
    }

    dosenDropdown.setSelectedIndex(indexDosen);
  }//GEN-LAST:event_tableMataKuliahMouseClicked

  private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
    // TODO add your handling code here:
    try {
      inputKosongException();
      String metodePembelajaran = "";
      String kelas = "";
      int selectedIndex = dosenDropdown.getSelectedIndex();
      Dosen selectedDosen = listDosen.get(selectedIndex);

      if (onlineCheckBox.isSelected() && offlineCheckBox.isSelected()) {
        metodePembelajaran = "Hybrid";
        kelas = ruangKelasGroup.getSelection().getActionCommand();
      } else if (onlineCheckBox.isSelected()) {
        metodePembelajaran = "Online";
        kelas = "Online";
      } else {
        metodePembelajaran = "Offline";
        kelas = ruangKelasGroup.getSelection().getActionCommand();
      }

      if (action.equals("Tambah")) {
        MataKuliah mk = new MataKuliah(matakuliahInput.getText(), deskripsiInput.getText(), metodePembelajaran, kelas, selectedDosen);
        mataKuliahControl.insertDataMataKuliah(mk);
      } else {
        MataKuliah mk = new MataKuliah(selectedId, matakuliahInput.getText(), deskripsiInput.getText(), metodePembelajaran, kelas, selectedDosen);
        mataKuliahControl.updateDataMataKuliah(mk);
      }

      clearText();
      showMataKuliah();
      setComponent(false);
      setRadioKelas(false);
      ruangKelasGroup.clearSelection();

      setEditDeleteBtn(rootPaneCheckingEnabled);

    } catch (InputEmptyException e) {
      JOptionPane.showMessageDialog(this, e.getMessage());
    }
  }//GEN-LAST:event_saveBtnActionPerformed

  private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
    // TODO add your handling code here:
    setComponent(false);
    setEditDeleteBtn(false);
    clearText();
  }//GEN-LAST:event_cancelBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MataKuliahView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new MataKuliahView().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addBtn;
  private javax.swing.JButton cancelBtn;
  private javax.swing.JPanel containerPanel;
  private javax.swing.JPanel contentPanel;
  private javax.swing.JLabel courseIcon;
  private javax.swing.JLabel courseLabel;
  private javax.swing.JPanel coursePanel;
  private javax.swing.JButton deleteBtn;
  private javax.swing.JTextField deskripsiInput;
  private javax.swing.JLabel deskripsiLabel;
  private javax.swing.JComboBox<String> dosenDropdown;
  private javax.swing.JLabel dosenLabel;
  private javax.swing.JButton editBtn;
  private javax.swing.JPanel headerPanel;
  private javax.swing.JTextField inputSearch;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTable1;
  private javax.swing.JLabel kelasLabel;
  private javax.swing.JLabel lecturerIcon;
  private javax.swing.JLabel lecturerLabel;
  private javax.swing.JPanel lecturerPanel;
  private javax.swing.JLabel logo;
  private javax.swing.JTextField matakuliahInput;
  private javax.swing.JLabel matakuliahLabel;
  private javax.swing.JLabel metodeLabel;
  private javax.swing.JCheckBox offlineCheckBox;
  private javax.swing.JCheckBox onlineCheckBox;
  private javax.swing.JRadioButton radio3315;
  private javax.swing.JRadioButton radio3318;
  private javax.swing.JRadioButton radio3421;
  private javax.swing.JRadioButton radio3422;
  private javax.swing.ButtonGroup ruangKelasGroup;
  private javax.swing.JButton saveBtn;
  private javax.swing.JButton searchBtn;
  private javax.swing.JPanel sidebarPanel;
  private javax.swing.JTable tableMataKuliah;
  private javax.swing.JLabel titleContent;
  // End of variables declaration//GEN-END:variables
}
